http:
  routers:
    projects-router:
      entryPoints:
        - web
      rule: "Path(`/`)"
      service: projects-service

    fastapi-pi-sense-router:
      entryPoints:
        - web
      rule: "PathPrefix(`/fastapi-pi-sense`)"
      service: fastapi-pi-sense-service

    nirl-qdms-router-dev:
      entryPoints:
        - web
      rule: "PathPrefix(`/nirl-qdms`)"
      priority: 10
      middlewares:
        - nirl-qdms-prefix-strip-dev
      service: nirl-qdms-service-dev

  middlewares:
    nirl-qdms-prefix-strip-dev:
      stripPrefix:
        prefixes:
          - "/nirl-qdms"
      

  services:
    projects-service:
      loadBalancer:
        servers:
          - url: "http://local-projects:80"

    fastapi-pi-sense-service:
      loadBalancer:
        servers:
          - url: "http://fastapi-pi-sense-container:8000"

    nirl-qdms-service-dev:
      loadBalancer:
        servers:
          - url: "http://nirl-qdms-nginx-dev:80"